### PR TITLE
Fixes several Github issues with the API call and formatting of the place selector

### LINKED ISSUE #65: Error in console when entering a community name twice in a row
If you use the form input field to enter a community name, select that community, then enter another community name, several errors show up in the console. The first error reads like this:

> Error in callback for watcher "selected": "TypeError: Cannot read properties of null (reading 'latitude')"

### LINKED ISSUE #77: Errors in console / busted behavior if you click on a location missing cfd or aqi forecast
STR -- select Baranof Warm Springs from community selector with console open.  Then try to pick other places.

### LINKED ISSUE #79: Community search results are hidden behind the map
When you start typing in letters for a community name, the communities in the list are hidden behind the map. The z-index needs to be adjusted to allow for the community search results to be shown on top of the map.

### PR DESCRIPTION
**Pull request by BobTorgerson**
This PR modifies the place selector code such that it waits until a community has been selected before setting the community name, which was resulting in the console errors identified in #65. It also changes the CSS for the mb-6 class such that in that scoped version of that class, it has a large z-index to always sit on top of the map for all of its search results as identified in #79. 

Finally, the PR contains a change to the conditional formatting of the FireAPIOutput component that more explicitly shows what data has been returned. Three places to test for sure are Fairbanks, Afognak, and Baranof Warm Springs. In Fairbanks, the cdf and AQI forecasts are available, in Afognak, the AQI forecasts are only available, and in the Baranof Warm Springs, none of it is available and it will state that there is no data available for this location.

Closes #65
Closes #77 
Closes #79

### CODE REVIEW

File: src/components/PlaceSelector.vue [hunk 1]
```diff
@@ -21,14 +25,25 @@
...
+            Clear Location
+          </b-button>
+        </div>
       </div>
     </div>
   </div>
 </template>
-<style lang="scss" scoped></style>
+<style lang="scss" scoped>
+.mb-6 {
```
Comment (brucecrevensten) [inline src/components/PlaceSelector.vue:42]: Don't modify the Bulma class; adjust to be its own class/style.

File: src/components/PlaceSelector.vue [hunk 2]
```diff
@@ -11,7 +11,11 @@
             placeholder="e.g. Fairbanks"
             clearable
             clear-on-select
-            @select="(option) => (community = option)"
+            @select="
```
Comment (brucecrevensten) [inline src/components/PlaceSelector.vue:14]: I'm not totally sure I understand why this works!  Let's talk about it

File: src/components/FireAPIOutput.vue [hunk 3]
```diff
@@ -15,7 +46,7 @@
         >
       </h5>
       <div class="content is-size-4">
-        <p>
+        <p v-if="apiOutput.cfd">
```
Comment (brucecrevensten) [inline src/components/FireAPIOutput.vue:49]: We may want to sharpen this a little more with testing also for the actual CFD object properties.  Pull it into its own function to isolate the logic.

Comment (brucecrevensten) [reply src/components/FireAPIOutput.vue:49]: Actually also clean up this and the relationship between logic in lines 33-36

File: src/components/FireAPIOutput.vue [hunk 4]
```diff
@@ -4,7 +4,38 @@
     <div v-if="loadingData" class="spinner">
       <div></div>
     </div>
-    <div class="container" v-if="!loadingData && selected && apiOutput && apiOutput.cfd">
+    <div
+      class="container"
+      v-if="
+        !loadingData &&
```
Comment (brucecrevensten) [inline src/components/FireAPIOutput.vue:10]: Let's pull this out of HTML and into its own function

**Review by brucecrevensten — CHANGES_REQUESTED** [review]
